title: Miguel López | Aerospace Systems & Software
email: miguelcllopez@gmail.com
description: >- # The ">-" allows writing in multiple lines
  Aerospace Engineer specializing in MBSE, Critical Flight Software (C++), and Space Systems.
baseurl: "" 
url: "https://miguelcllopez.github.io/" 
author: Miguel López Cordero

# Build Configuration
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
